### ISSUE TITLE
WARNING when trying to use SENDFIELD console command

### ISSUE THREAD

**Issue by LeonardoTheMutant** [bitten2up/sendcolor-srb2#1]
WARNING: DOWNLOAD/sendcolor.lua:234: attempt to concatenate local 'fieldnum' (a nil value)
stack traceback:
    DOWNLOAD/sendcolor.lua:234: in function <DOWNLOAD/sendcolor.lua:233>

**Comment by bitten2up** [comment]
can you provide some more of the logs please. also did the server crash? did sendcolor stop working?

**Comment by LeonardoTheMutant** [comment]
Nothing crashed or stopped working (as long as I've used). Here's the full log:
`Compiled for SDL version: 2.0.20
Linked with SDL version: 2.0.20
Setting up SRB2...


Sonic Robo Blast 2
Copyright (C) 1998-2023 by Sonic Team Junior

This program comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it
and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2 of
the License, or (at your option) any later version.
See the 'LICENSE.txt' file for details.

Sonic the Hedgehog and related characters are trademarks of SEGA.
We do not claim ownership of SEGA's intellectual property used
in this program.

M_StartupLocale...
Looking for WADs in: SRB2WADDIR,.
Z_Init(): Init zone memory allocation daemon. 
System memory: 4095MB - Free: 4095MB
I_InitializeTime()...
W_InitMultipleFiles(): Adding IWAD and main PWADs.
Added file C:\Games\SRB2\srb2.pk3 (12647 lumps)
Loading SOC from C:\Games\SRB2\srb2.pk3|SOC/SOC_TITL
Loading SOC from C:\Games\SRB2\srb2.pk3|SOC/SOC_LETR
Added file C:\Games\SRB2\zones.pk3 (141 lumps)
Loading SOC from C:\Games\SRB2\zones.pk3|SOC/SOC_EMBM.txt
Loading SOC from C:\Games\SRB2\zones.pk3|SOC/SOC_HEAD.txt
Loading SOC from C:\Games\SRB2\zones.pk3|SOC/SOC_SECR.txt
Loading SOC from C:\Games\SRB2\zones.pk3|SOC/Tutorial.txt
Added file C:\Games\SRB2\player.dta (1869 lumps)
Loading SOC from C:\Games\SRB2\player.dta|SOC_PLAY
Added file C:\Games\SRB2\patch.pk3 (14 lumps)
Added file C:\Games\SRB2\music.dta (181 lumps)
I_StartupGraphics()...
NOTE: Under SDL2, all modes are supported on all platforms.
Under opengl, fullscreen only supports native desktop resolution.
Under software, the mode is stretched up to desktop resolution.
 0: 1920x1200
 1: 1920x1080
 2: 1680x1050
 3: 1600x1200
 4: 1600x900
 5: 1366x768
 6: 1440x900
 7: 1280x1024
 8: 1280x960
 9: 1280x800
10: 1280x720
11: 1152x864
12: 1024x768
13: 800x600
14: 640x480
15: 640x400
16: 320x240
17: 320x200
Current Video Mode
 320x200 at 16 bit color
 Stored in system memory
CPU Info: 486: 1, 586: 1, MMX: 1, 3DNow: 0, MMXExt: 0, SSE2: 1
Number of console HUD lines is now 5
I_InitJoystick()...
HU_LoadGraphics()...
executing config.cfg
ERROR: Mix_LoadMUS_RW: Unrecognized audio format
ERROR: Music _clear could not be loaded: engine failure!
Levels will end after 5 minutes.
Default resolution: 800 x 600 (8 bits)
M_Init(): Init miscellaneous info.
R_Init(): Init SRB2 refresh daemon.
R_LoadTextures()...
P_InitPicAnims()...
R_InitSprites()...
srb2.pk3 added 5396 frames in 385 sprites
R_InitColormaps()...
S_InitSfxChannels(): Setting up sound channels.
libopenmpt version: 0.4.7+r12088.pkg
libopenmpt build date: 2019-09-23T10:02:47.236448Z
ST_Init(): Init status bar.
D_CheckNetGame(): Checking network game status.
executing .\autoexec.cfg
Logfile: .\logs\log-2023-07-10_18-46-01.txt
Entering main game loop...
===========================================================================
                   We hope you enjoy this game as
                     much as we did making it!
                            ...wait. =P
===========================================================================
Sonic Robo Blast 2 v2.2.11 (May 16 2023 18:21:59 2c689bae master) SDL Windows 32-bit 
Binding to 0.0.0.0
Network system buffer: 8Kb
Network system buffer set to: 64Kb
Contacting the server...
DOWNLOAD/sendcolor.lua...
Downloading DOWNLOAD/sendcolor.lua...(done)
Added file DOWNLOAD/sendcolor.lua (1 lumps)
Loading Lua script from DOWNLOAD/sendcolor.lua
Pardon me while I initialize the Lua scripting interface...
Skincolor SKINCOLOR_SEND0 allocated.
Skincolor SKINCOLOR_SEND1 allocated.
Skincolor SKINCOLOR_SEND2 allocated.
Skincolor SKINCOLOR_SEND3 allocated.
Skincolor SKINCOLOR_SEND4 allocated.
Skincolor SKINCOLOR_SEND5 allocated.
Skincolor SKINCOLOR_SEND6 allocated.
Skincolor SKINCOLOR_SEND7 allocated.
Skincolor SKINCOLOR_SEND8 allocated.
Skincolor SKINCOLOR_SEND9 allocated.
Skincolor SKINCOLOR_SEND10 allocated.
Skincolor SKINCOLOR_SEND11 allocated.
Skincolor SKINCOLOR_SEND12 allocated.
Skincolor SKINCOLOR_SEND13 allocated.
Skincolor SKINCOLOR_SEND14 allocated.
Skincolor SKINCOLOR_SEND15 allocated.
Skincolor SKINCOLOR_SEND16 allocated.
Skincolor SKINCOLOR_SEND17 allocated.
Skincolor SKINCOLOR_SEND18 allocated.
Skincolor SKINCOLOR_SEND19 allocated.
Skincolor SKINCOLOR_SEND20 allocated.
Skincolor SKINCOLOR_SEND21 allocated.
Skincolor SKINCOLOR_SEND22 allocated.
Skincolor SKINCOLOR_SEND23 allocated.
Skincolor SKINCOLOR_SEND24 allocated.
Skincolor SKINCOLOR_SEND25 allocated.
Skincolor SKINCOLOR_SEND26 allocated.
Skincolor SKINCOLOR_SEND27 allocated.
Skincolor SKINCOLOR_SEND28 allocated.
Skincolor SKINCOLOR_SEND29 allocated.
Skincolor SKINCOLOR_SEND30 allocated.
Skincolor SKINCOLOR_SEND31 allocated.
Skincolor SKINCOLOR_SEND32 allocated.
Added command "sendfield"
Added command "sendcolor"
Added command "savecolor"
Added command "setauto"
Added command "colorban"
Added command "removeplayercolor"
Added command "allowresendplayer"
Added command "clearcolors"
colorlock set to Off
allowresend set to -1
No maps added
Sending join request...
Join accepted, waiting for complete game state...
.\$$$.sav...
Downloading .\$$$.sav...(done)
Loading savegame length 113645
allowresend set to -1
colorlock set to Off
Map is now "MAP13: Arid Canyon Zone  1"
*LeoTM has joined the game (player 1)
sendfield cancel
<LeoTM> Hello there, admins
$nodes
01: LeoTM - node 00 - self
$listwad
There are 6 files loaded:
   05: sendcolor.lua
   04: music.dta
 * 03: patch.pk3
 * 02: player.dta
 * 01: zones.pk3
 IWAD: srb2.pk3
$color crimson
$sendfield
WARNING: DOWNLOAD/sendcolor.lua:234: attempt to concatenate local 'fieldnum' (a nil value)
stack traceback:
    DOWNLOAD/sendcolor.lua:234: in function <DOWNLOAD/sendcolor.lua:233>
$colorban
Only the server or a remote admin can use this.
$clearcolors
Only the server or a remote admin can use this.
$satauto
Unknown command 'satauto'
$setauto
setauto <colorname> [<filename>]
$setauto SKINCOLOR_SEND0
Could not opensendcolor.txt
$allowresendplayer 
Only the server or a remote admin can use this.
$savecolor
savecolor <colorname> [<filename>]
$savecolor crimson meme.txt
Saved color Crimson
$color skincolor_send0
"skincolor_send0" is not a possible value for "color"
$color skincolor_send00
"skincolor_send00" is not a possible value for "color"
$color skincolor_send32
"skincolor_send32" is not a possible value for "color"
$help color
Variable color:
  flags :ACTION 
 Possible values:
  1  : White
  2  : Bone
  3  : Cloudy
  4  : Grey
  5  : Silver
  6  : Carbon
  7  : Jet
  8  : Black
  9  : Aether
  10 : Slate
  11 : Bluebell
  12 : Pink
  13 : Yogurt
  14 : Brown
  15 : Bronze
  16 : Tan
  17 : Beige
  18 : Moss
  19 : Azure
  20 : Lavender
  21 : Ruby
  22 : Salmon
  23 : Red
  24 : Crimson
  25 : Flame
  26 : Ketchup
  27 : Peachy
  28 : Quail
  29 : Sunset
  30 : Copper
  31 : Apricot
  32 : Orange
  33 : Rust
  34 : Gold
  35 : Sandy
  36 : Yellow
  37 : Olive
  38 : Lime
  39 : Peridot
  40 : Apple
  41 : Green
  42 : Forest
  43 : Emerald
  44 : Mint
  45 : Seafoam
  46 : Aqua
  47 : Teal
  48 : Wave
  49 : Cyan
  50 : Sky
  51 : Cerulean
  52 : Icy
  53 : Sapphire
  54 : Cornflower
  55 : Blue
  56 : Cobalt
  57 : Vapor
  58 : Dusk
  59 : Pastel
  60 : Purple
  61 : Bubblegum
  62 : Magenta
  63 : Neon
  64 : Violet
  65 : Lilac
  66 : Plum
  67 : Raspberry
  68 : Rosy
 Current value: Crimson
$sendfield
WARNING: DOWNLOAD/sendcolor.lua:234: attempt to concatenate local 'fieldnum' (a nil value)
stack traceback:
    DOWNLOAD/sendcolor.lua:234: in function <DOWNLOAD/sendcolor.lua:233>
$quit
I_ShutdownGraphics(): shut down
Shutting down joy system
I_Joystick: SDL's Joystick system has been shutdown
I_ShutdownTcpDriver: shut down
I_ShutdownSystem(): end of logstream.
`

**Comment by LeonardoTheMutant** [comment]
[log-2023-07-10_18-46-01.txt](https://github.com/bitten2up/sendcolor-srb2/files/12005711/log-2023-07-10_18-46-01.txt)
(should've just drop the .log itself)

**Comment by bitten2up** [comment]
> [log-2023-07-10_18-46-01.txt](https://github.com/bitten2up/sendcolor-srb2/files/12005711/log-2023-07-10_18-46-01.txt) (should've just drop the .log itself)

oh ok i understand now, run `sendcolor`, sendfield is used internally

**Comment by LeonardoTheMutant** [comment]
It shows that it can't open the `sendcolor.txt`, that's probably how it supposed to work. I am quite unknown what the script actually does and from what I've already read it's custom color save/load from local file

**EDIT:** I actually made `sendcolor` work and the debug shows that my color applied successfully with skincolor on character matching

**Comment by bitten2up** [comment]
> It shows that it can't open the `sendcolor.txt`, that's probably how it supposed to work. I am quite unknown what the script actually does and from what I've already read it's custom color save/load from local file
> 
> **EDIT:** I actually made `sendcolor` work and the debug shows that my color applied successfully with skincolor on character matching

is it fine to close the issue
