### ISSUE TITLE
Return text of the SETAUTO is missing a space

### ISSUE THREAD

**Issue by LeonardoTheMutant** [bitten2up/sendcolor-srb2#2]
The following command is missing a space symbol in the return message:
```
$setauto
setauto <colorname> [<filename>]
$setauto crimson mycolor.txt
Could not openmycolor.txt
```

**Comment by bitten2up** [comment]
ill look into this in 2 weeks, as i wont be home. feel free to look into it and create a pull request

**Comment by bitten2up** [comment]
should be fixed by https://github.com/bitten2up/sendcolor-srb2/commit/467b9e273a70d3641ff58bdcf9432c73a4cd549f let me know if it fixes your issue

**Comment by bitten2up** [comment]
im going to say its fixed, but comment if its still happening
